server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      
phonebook:
 messages:
          saveSuccess: contact saved successfully
          updateSuccess: contact updated successfully
          failedSave: ubable to save contact
